package com.fulviotarable;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Fulvio
 */
public class BibliotecarioVista extends JFrame{
        
    /**
     * Creates new form BibliotecarioVista
     */
    public BibliotecarioVista() {
        
// Imposta la GUI secondo lo stile del Sistema Operativo Windows        
        try {UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            } catch (Exception e) 
                {e.printStackTrace();
                }

// Avvia la costruzione della GUI
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gruppoProfiliRedattori = new javax.swing.ButtonGroup();
        pannelloElenchiLibri = new javax.swing.JTabbedPane();
        pannelloLibriDaCercare = new javax.swing.JPanel();
        barreScorrimentoPannelloLibriDaCercare = new javax.swing.JScrollPane();
        areaTestoLibriDaCercare = new javax.swing.JTextArea();
        pannelloLibriNonTrovati = new javax.swing.JPanel();
        barreScorrimentoPannelloLibriNonTrovati = new javax.swing.JScrollPane();
        areaTestoLibriNonTrovati = new javax.swing.JTextArea();
        pannelloMenu = new javax.swing.JPanel();
        pannelloCriteriDiCorrispondenza = new javax.swing.JPanel();
        Autore = new javax.swing.JCheckBox();
        Titolo = new javax.swing.JCheckBox();
        Anno = new javax.swing.JCheckBox();
        caricaLibreria = new javax.swing.JButton();
        statoRicerca = new javax.swing.JProgressBar();
        estensioneFile = new javax.swing.JComboBox<>();
        posizioneLibreria = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cercaInLibreria = new javax.swing.JButton();
        barraDiStato = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        totaleLibriPresenti = new javax.swing.JTextField();
        menuBarBibliotecario = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        fileApri = new javax.swing.JMenuItem();
        menuRedattori = new javax.swing.JMenu();
        profiloRedattore1 = new javax.swing.JRadioButtonMenuItem();
        profiloRedattore2 = new javax.swing.JRadioButtonMenuItem();
        profiloRedattore3 = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Applicazione Bibliotecario");
        setLocation(100,100);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(500, 500));

        pannelloElenchiLibri.setName("pannelloElenchiLibri"); // NOI18N

        pannelloLibriDaCercare.setName("pannelloLibriDaCercare"); // NOI18N

        barreScorrimentoPannelloLibriDaCercare.setName("barreScorrimentoPannelloLibriDaCercare"); // NOI18N

        areaTestoLibriDaCercare.setEditable(false);
        areaTestoLibriDaCercare.setColumns(20);
        areaTestoLibriDaCercare.setLineWrap(true);
        areaTestoLibriDaCercare.setRows(25);
        areaTestoLibriDaCercare.setName("areaTestoLibriDaCercare"); // NOI18N
        barreScorrimentoPannelloLibriDaCercare.setViewportView(areaTestoLibriDaCercare);
        areaTestoLibriDaCercare.getAccessibleContext().setAccessibleName("areaTestoLibriDaCercare");

        javax.swing.GroupLayout pannelloLibriDaCercareLayout = new javax.swing.GroupLayout(pannelloLibriDaCercare);
        pannelloLibriDaCercare.setLayout(pannelloLibriDaCercareLayout);
        pannelloLibriDaCercareLayout.setHorizontalGroup(
            pannelloLibriDaCercareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barreScorrimentoPannelloLibriDaCercare, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );
        pannelloLibriDaCercareLayout.setVerticalGroup(
            pannelloLibriDaCercareLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barreScorrimentoPannelloLibriDaCercare, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
        );

        pannelloElenchiLibri.addTab("Libri da CERCARE", pannelloLibriDaCercare);

        pannelloLibriNonTrovati.setName("pannelloLibriNonTrovati"); // NOI18N

        barreScorrimentoPannelloLibriNonTrovati.setName("barreScorrimentoPannelloLibriNonTrovati"); // NOI18N

        areaTestoLibriNonTrovati.setEditable(false);
        areaTestoLibriNonTrovati.setColumns(20);
        areaTestoLibriNonTrovati.setLineWrap(true);
        areaTestoLibriNonTrovati.setName("areaTestoLibriNonTrovati"); // NOI18N
        barreScorrimentoPannelloLibriNonTrovati.setViewportView(areaTestoLibriNonTrovati);

        javax.swing.GroupLayout pannelloLibriNonTrovatiLayout = new javax.swing.GroupLayout(pannelloLibriNonTrovati);
        pannelloLibriNonTrovati.setLayout(pannelloLibriNonTrovatiLayout);
        pannelloLibriNonTrovatiLayout.setHorizontalGroup(
            pannelloLibriNonTrovatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
            .addGroup(pannelloLibriNonTrovatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(barreScorrimentoPannelloLibriNonTrovati, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE))
        );
        pannelloLibriNonTrovatiLayout.setVerticalGroup(
            pannelloLibriNonTrovatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
            .addGroup(pannelloLibriNonTrovatiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(barreScorrimentoPannelloLibriNonTrovati, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE))
        );

        pannelloElenchiLibri.addTab("Libri NON trovati", pannelloLibriNonTrovati);

        pannelloMenu.setName("pannelloMenu"); // NOI18N

        pannelloCriteriDiCorrispondenza.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Criteri di Corrispondenza", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        pannelloCriteriDiCorrispondenza.setName("pannelloCriteriDiCorrispondenza"); // NOI18N

        Autore.setSelected(true);
        Autore.setText("Autore");
        Autore.setToolTipText("Impone la ricerca dello stesso Autore");
        Autore.setName("Autore"); // NOI18N

        Titolo.setSelected(true);
        Titolo.setText("Titolo del Libro");
        Titolo.setToolTipText("Impone la ricerca dello stesso Titolo");
        Titolo.setName("Titolo"); // NOI18N

        Anno.setText("Anno");
        Anno.setToolTipText("Impone la ricerca dello stesso Anno");
        Anno.setName("Anno"); // NOI18N

        caricaLibreria.setText("Carica Libreria");
        caricaLibreria.setName("caricaLibreria"); // NOI18N
        caricaLibreria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caricaLibreriaActionPerformed(evt);
            }
        });

        statoRicerca.setName("statoRicerca"); // NOI18N

        estensioneFile.setMaximumRowCount(4);
        estensioneFile.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ".epub", ".pdf", ".rar", ".zip" }));
        estensioneFile.setSelectedIndex(1);
        estensioneFile.setToolTipText("Scelta del formato");
        estensioneFile.setName("estensioneFile"); // NOI18N

        posizioneLibreria.setToolTipText("Specifica la posizione di default di ricerca dei libri, secondo la notazione  del FileSystem");
        posizioneLibreria.setName("posizioneLibreria"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Libreria");
        jLabel1.setName("jLabel1"); // NOI18N

        cercaInLibreria.setText("CERCA in Libreria");
        cercaInLibreria.setName("cercaInLibreria"); // NOI18N
        cercaInLibreria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cercaInLibreriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pannelloCriteriDiCorrispondenzaLayout = new javax.swing.GroupLayout(pannelloCriteriDiCorrispondenza);
        pannelloCriteriDiCorrispondenza.setLayout(pannelloCriteriDiCorrispondenzaLayout);
        pannelloCriteriDiCorrispondenzaLayout.setHorizontalGroup(
            pannelloCriteriDiCorrispondenzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannelloCriteriDiCorrispondenzaLayout.createSequentialGroup()
                .addGroup(pannelloCriteriDiCorrispondenzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pannelloCriteriDiCorrispondenzaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pannelloCriteriDiCorrispondenzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannelloCriteriDiCorrispondenzaLayout.createSequentialGroup()
                                .addComponent(Autore)
                                .addGap(18, 18, 18)
                                .addComponent(Titolo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Anno))
                            .addGroup(pannelloCriteriDiCorrispondenzaLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(posizioneLibreria))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pannelloCriteriDiCorrispondenzaLayout.createSequentialGroup()
                        .addComponent(caricaLibreria, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statoRicerca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pannelloCriteriDiCorrispondenzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(estensioneFile, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cercaInLibreria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pannelloCriteriDiCorrispondenzaLayout.setVerticalGroup(
            pannelloCriteriDiCorrispondenzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannelloCriteriDiCorrispondenzaLayout.createSequentialGroup()
                .addGroup(pannelloCriteriDiCorrispondenzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Autore)
                    .addComponent(Anno)
                    .addComponent(Titolo)
                    .addComponent(estensioneFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pannelloCriteriDiCorrispondenzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(posizioneLibreria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(pannelloCriteriDiCorrispondenzaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(caricaLibreria)
                    .addComponent(statoRicerca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cercaInLibreria))
                .addContainerGap())
        );

        javax.swing.GroupLayout pannelloMenuLayout = new javax.swing.GroupLayout(pannelloMenu);
        pannelloMenu.setLayout(pannelloMenuLayout);
        pannelloMenuLayout.setHorizontalGroup(
            pannelloMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pannelloCriteriDiCorrispondenza, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pannelloMenuLayout.setVerticalGroup(
            pannelloMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pannelloCriteriDiCorrispondenza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        barraDiStato.setName("barraDiStato"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Presenti in Libreria:");
        jLabel2.setName("jLabel2"); // NOI18N

        totaleLibriPresenti.setEditable(false);
        totaleLibriPresenti.setName("totaleLibriPresenti"); // NOI18N

        javax.swing.GroupLayout barraDiStatoLayout = new javax.swing.GroupLayout(barraDiStato);
        barraDiStato.setLayout(barraDiStatoLayout);
        barraDiStatoLayout.setHorizontalGroup(
            barraDiStatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraDiStatoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totaleLibriPresenti, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        barraDiStatoLayout.setVerticalGroup(
            barraDiStatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraDiStatoLayout.createSequentialGroup()
                .addGroup(barraDiStatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(totaleLibriPresenti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        menuBarBibliotecario.setName("menuBarBibliotecario"); // NOI18N

        menuFile.setText("File");
        menuFile.setName("menuFile"); // NOI18N

        fileApri.setLabel("Apri Elenco");
        fileApri.setName("fileApri"); // NOI18N
        fileApri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileApriActionPerformed(evt);
            }
        });
        menuFile.add(fileApri);

        menuBarBibliotecario.add(menuFile);

        menuRedattori.setText("Redattori");
        menuRedattori.setName("menuRedattori"); // NOI18N

        gruppoProfiliRedattori.add(profiloRedattore1);
        profiloRedattore1.setSelected(true);
        profiloRedattore1.setText("Profilo Redattore 1");
        profiloRedattore1.setName("profiloRedattore1"); // NOI18N
        profiloRedattore1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profiloRedattore1ActionPerformed(evt);
            }
        });
        menuRedattori.add(profiloRedattore1);

        gruppoProfiliRedattori.add(profiloRedattore2);
        profiloRedattore2.setText("Profilo Redattore 2");
        profiloRedattore2.setName("profiloRedattore2"); // NOI18N
        menuRedattori.add(profiloRedattore2);

        gruppoProfiliRedattori.add(profiloRedattore3);
        profiloRedattore3.setText("Profilo Redattore 3");
        profiloRedattore3.setName("profiloRedattore3"); // NOI18N
        menuRedattori.add(profiloRedattore3);

        menuBarBibliotecario.add(menuRedattori);

        setJMenuBar(menuBarBibliotecario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pannelloElenchiLibri)
            .addComponent(pannelloMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(barraDiStato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pannelloMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pannelloElenchiLibri, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barraDiStato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fileApriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileApriActionPerformed
        statoRicerca.setIndeterminate(false);
        try {
            showOpenFileDialog();
        } catch (FileNotFoundException FNFEx) {
//            Logger.getLogger(BibliotecarioVista.class.getName()).log(Level.SEVERE, null, FNFEx);
        } catch (IOException IOEx) {
//            Logger.getLogger(BibliotecarioVista.class.getName()).log(Level.SEVERE, null, IOEx);
        }
    }//GEN-LAST:event_fileApriActionPerformed

    private void profiloRedattore1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profiloRedattore1ActionPerformed
// Creazione di un profilo Redattore corrispondente        
        ProfiloRedattore pr1 = new ProfiloRedattore();
        pr1.setFineAutore('\u002D');
        pr1.setFineTitolo('\u002D');
        pr1.setInizioAnno('\u0028');
        pr1.setFineAnno('\u0029');
        pr1.setRegexTrovaAnno("[\u0028]+[\\d]{4}+[\u0029]");
        pr1.setRegexTrovaTitolo("[A-Z]*[a-z]+[\\D]");        
    }//GEN-LAST:event_profiloRedattore1ActionPerformed

    private void caricaLibreriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caricaLibreriaActionPerformed
        try {
//        statoRicerca.setIndeterminate(true);
            // Invoca il metodo caricaLibreria
            BibliotecarioControllore.caricaLibreria(posizioneLibreria.getText());
        } catch (FileNotFoundException | NullPointerException ex) {
//            Logger.getLogger(BibliotecarioVista.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_caricaLibreriaActionPerformed

    private void cercaInLibreriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cercaInLibreriaActionPerformed
// Invoca il metodo cercaInLibreria
        BibliotecarioControllore.cercaInLibreria();
    }//GEN-LAST:event_cercaInLibreriaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Anno;
    private javax.swing.JCheckBox Autore;
    private javax.swing.JCheckBox Titolo;
    protected static javax.swing.JTextArea areaTestoLibriDaCercare;
    protected javax.swing.JTextArea areaTestoLibriNonTrovati;
    private javax.swing.JPanel barraDiStato;
    private javax.swing.JScrollPane barreScorrimentoPannelloLibriDaCercare;
    private javax.swing.JScrollPane barreScorrimentoPannelloLibriNonTrovati;
    private javax.swing.JButton caricaLibreria;
    private javax.swing.JButton cercaInLibreria;
    private javax.swing.JComboBox<String> estensioneFile;
    private javax.swing.JMenuItem fileApri;
    private javax.swing.ButtonGroup gruppoProfiliRedattori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar menuBarBibliotecario;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuRedattori;
    private javax.swing.JPanel pannelloCriteriDiCorrispondenza;
    private javax.swing.JTabbedPane pannelloElenchiLibri;
    private javax.swing.JPanel pannelloLibriDaCercare;
    private javax.swing.JPanel pannelloLibriNonTrovati;
    private javax.swing.JPanel pannelloMenu;
    protected javax.swing.JTextField posizioneLibreria;
    private javax.swing.JRadioButtonMenuItem profiloRedattore1;
    private javax.swing.JRadioButtonMenuItem profiloRedattore2;
    private javax.swing.JRadioButtonMenuItem profiloRedattore3;
    protected javax.swing.JProgressBar statoRicerca;
    protected javax.swing.JTextField totaleLibriPresenti;
    // End of variables declaration//GEN-END:variables

/**
 *  Apre la finestra di Dialogo di Scelta del File di Testo da elaborare 
 *    
 * @throws java.io.FileNotFoundException 
 *
 */   
    public void showOpenFileDialog() throws FileNotFoundException, IOException
    { JFileChooser fileChooser = new JFileChooser();
// posiziona l'indice nella directory utente        
    fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
// cerca i soli file con estensione .txt
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("File di testo (*.txt)", "txt"));
        fileChooser.setAcceptAllFileFilterUsed(true);
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) 
        {

// Una volta ottenuto il nome del file lo passa al Controllore
// Stampa a console il nome del file selezionato
            File selectedFile = fileChooser.getSelectedFile();            
            File fileSelezionato = new File(selectedFile.getAbsolutePath());

//        System.out.println("File Selezionato: " + fileSelezionato.toString());
// Invoco il metodo di caricaElencoLibri di Bibliotecario Controllore per caricare il file
            BibliotecarioControllore.caricaElencoLibri(fileSelezionato);
        }        
    }

// Mostra a video il messaggio di errore che si è verificato
	
	public void mostraMessaggioErrore(String errorMessage){		
		JOptionPane.showMessageDialog(this, errorMessage);
    }
}